[libraries]
com-github-ajalt-clikt-clikt = "com.github.ajalt.clikt:clikt:5.0.3"
org-jetbrains-kotlinx-kotlinx-serialization-bom = "org.jetbrains.kotlinx:kotlinx-serialization-bom:1.9.0"

[plugins]
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
org-jmailen-kotlinter = "org.jmailen.kotlinter:5.3.0"
