[libraries]
org-apache-logging-log4j-log4j-core = "org.apache.logging.log4j:log4j-core:2.25.3"
org-jmailen-gradle-kotlinter-gradle = "org.jmailen.gradle:kotlinter-gradle:5.4.2"

[plugins]
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
org-jmailen-kotlinter = "org.jmailen.kotlinter:5.4.2"
