[versions]
kotlin = "2.3.10"
kotlinx-coroutines = "1.10.2"

[libraries]
com-zegreatrob-testmints-standard = "com.zegreatrob.testmints:standard:12.6.1"
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
org-jetbrains-kotlin-kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
org-jetbrains-kotlinx-kotlinx-serialization-bom = "org.jetbrains.kotlinx:kotlinx-serialization-bom:1.10.0"

[plugins]
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:1.1.0"
org-jetbrains-kotlin-jvm = "org.jetbrains.kotlin.jvm:2.3.10"
org-jetbrains-kotlin-multiplatform = "org.jetbrains.kotlin.multiplatform:2.3.10"
